name: Build and upload nightly ipa

on:
  push:
    branches: [none]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Get commit SHA
        id: commitinfo
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build
        run: xcodebuild -scheme Ferrite -configuration Release archive -archivePath build/Ferrite.xcarchive CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Package ipa
        run: |
          mkdir Payload
          cp -r build/Ferrite.xcarchive/Products/Applications/Ferrite.app Payload
          zip -r Ferrite-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa Payload
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ferrite-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa
          path: Ferrite-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa
          if-no-files-found: error
