name: Build and upload release ipa

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Build
        run: xcodebuild -scheme Ferrite -configuration Release archive -archivePath build/Ferrite.xcarchive CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        env:
          IS_NIGHTLY: NO
      - name: Get app version
        run: |
          echo "app_version=$(/usr/libexec/plistbuddy -c Print:CFBundleShortVersionString: build/Ferrite.xcarchive/Products/Applications/Ferrite.app/Info.plist)" >> $GITHUB_ENV
      - name: Package ipa
        run: |
          mkdir Payload
          cp -r build/Ferrite.xcarchive/Products/Applications/Ferrite.app Payload
          zip -r Ferrite-iOS_v${{ env.app_version }}.ipa Payload
      - name: Create ipa zip
        run: |
          zip -j Ferrite-iOS_v${{ env.app_version }}.ipa.zip Ferrite-iOS_v${{ env.app_version }}.ipa
      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Ferrite-iOS_v${{ env.app_version }}.ipa.zip
